const jwt = require('jsonwebtoken')
const registerModel = require('../models/registerModel');
require('dotenv').config();
const secretKey = process.env.SECRET_KEY

const auth = async (req, res, next)=>{
    try {
        const cookieValue = req.cookies.jwt; //getting the cookie value, //here jwt is the name of the cookie we are trying to get
        const verifyUser = jwt.verify(cookieValue, secretKey ) //verifying that the cookie value matches the token created using the secret key
        console.log(verifyUser) //O/P { _id: '660e2e0a2201eefb34f4956b', iat: 1712207423 } here the _id refers to the _id of the user having a token generated by the scret key and using this resulted _id we can access thge og user data like below
        const user = await registerModel.findOne({_id: verifyUser._id});
        console.log(user);

        // impolementing logout functionality (its very very important)
        req.token = cookieValue;
        req.user = user;
        next();

    } catch (error) {
        res.status(401).send(error) 
    }
}

module.exports = auth;